export const GAMEPLAY_CONSTANTS = {
  // Hive Health and Difficulty
  HIVE: {
    BOSS_HP: 1000,
    ELITE_HP: 500,
    NORMAL_HP: 500,
    BOSS_DIFFICULTY: 20,
    ELITE_DIFFICULTY: 15,
    NORMAL_DIFFICULTY: 10,
  },

  // Rewards
  SCRAP_REWARDS: {
    HIVE_DESTROY: 75,
    ESCORT_COMPLETE: 50,
    OBJECTIVE_COMPLETE: 25,
    MISSION_WIN: 100,
    MISSION_LOSS_CONSOLATION: 10,
    ELITE_KILL: 10,
    BOSS_KILL: 25,
    LOOT_CRATE: 25,
  },

  XP_REWARDS: {
    MISSION_WIN: 50,
    MISSION_LOSS: 10,
    SURVIVAL_BONUS: 20,
    KILL: 10,
  },

  // Mission Scaling
  MISSION_SCALING: {
    BOSS_MULTIPLIER: 3,
    ELITE_MULTIPLIER: 2,
    NORMAL_MULTIPLIER: 1,
    RECOVER_COUNT_BOSS: 2,
    RECOVER_COUNT_ELITE: 1,
    OBJECTIVE_COUNT_BOSS: 3,
    OBJECTIVE_COUNT_ELITE: 2,
    OBJECTIVE_COUNT_DEFAULT: 3,
    DISTANCE_EXTRACTION_FACTOR: 0.4,
    DISTANCE_HIVE_FACTOR: 0.5,
  },

  // Costs
  RECRUITMENT_COST: 100,

  // Director
  DIRECTOR: {
    TURN_DURATION_MS: 10000,
    THREAT_PER_TURN: 10,
    MAX_SCALING_TURNS: 10,
    SCANNER_RADIUS: 5,
    THREAT_LOW: 30,
    THREAT_HIGH: 60,
    DIFFICULTY_EASY: 1,
    DIFFICULTY_MEDIUM: 2,
    DIFFICULTY_HARD: 3,
    STARTING_POINTS: 20,
    SPAWN_OFFSET_RANGE: 0.4,
    SPAWN_OFFSET_BASE: 0.2,
    POINT_GROWTH_RATE: 1.0,
  },

  // Items
  ITEMS: {
    DEFAULT_HEAL: 50,
    GRENADE_DAMAGE: 100,
    MINE_DAMAGE: 100,
    MINE_RADIUS: 1,
    SENTRY_DEFAULT_DAMAGE: 10,
    SENTRY_DEFAULT_FIRE_RATE: 500,
    SENTRY_DEFAULT_ACCURACY: 60,
    SENTRY_DEFAULT_RANGE: 6,
    BASE_USE_ITEM_TIME: 3000,
    BASE_PICKUP_TIME: 3000,
    BASE_COLLECT_TIME: 3000,
    BASE_EXTRACT_TIME: 5000,
    INTERACTION_RADIUS: 0.8,
    USE_ITEM_RANGE_THRESHOLD: 1.0,
  },

  // Engine
  ENGINE: {
    SPEED_NORMALIZATION_CONST: 30,
    UNIT_RADIUS: 0.3,
  },

  // Combat
  COMBAT: {
    MIN_DISTANCE: 0.1,
    MELEE_RANGE_BUFFER: 0.05,
    RANGED_RANGE_BUFFER: 0.5,
    MIN_HIT_CHANCE: 0,
    MAX_HIT_CHANCE: 1.0,
    STICKY_TARGET_SCORE_NORM: 100,
    HIT_CHANCE_NORM: 100,
  },

  // AI
  AI: {
    LOW_HP_THRESHOLD: 0.25,
    ISOLATION_RADIUS: 5,
    EXPLORATION_CHECK_INTERVAL: 1000,
    EXPLORATION_SWITCH_THRESHOLD: 0.7,
    RUSH_DISTANCE_THRESHOLD: 1.5,
    RETREAT_DISTANCE_FACTOR: 0.8,
    VIP_FLEE_DISTANCE: 5,
    VIP_FOLLOW_DISTANCE: 2,
    VIP_FLEE_SEARCH_MIN: 2,
    VIP_FLEE_SEARCH_MAX: 4,
  },

  // Movement
  MOVEMENT: {
    CENTER_OFFSET: 0.5,
    ARRIVAL_THRESHOLD: 0.05,
  },
} as const;

// Convenience exports
export const HIVE = GAMEPLAY_CONSTANTS.HIVE;
export const SCRAP_REWARDS = GAMEPLAY_CONSTANTS.SCRAP_REWARDS;
export const XP_REWARDS = GAMEPLAY_CONSTANTS.XP_REWARDS;
export const RECRUITMENT_COST = GAMEPLAY_CONSTANTS.RECRUITMENT_COST;
export const DIRECTOR = GAMEPLAY_CONSTANTS.DIRECTOR;
export const ITEMS = GAMEPLAY_CONSTANTS.ITEMS;
export const COMBAT = GAMEPLAY_CONSTANTS.COMBAT;
export const MOVEMENT = GAMEPLAY_CONSTANTS.MOVEMENT;
export const MISSION_SCALING = GAMEPLAY_CONSTANTS.MISSION_SCALING;
export const AI = GAMEPLAY_CONSTANTS.AI;
export const SPEED_NORMALIZATION_CONST =
  GAMEPLAY_CONSTANTS.ENGINE.SPEED_NORMALIZATION_CONST;
export const UNIT_RADIUS = GAMEPLAY_CONSTANTS.ENGINE.UNIT_RADIUS;
