import { describe, it, expect } from 'vitest';
import { TreeShipGenerator } from '../../generators/TreeShipGenerator';
import { MapDefinition, CellType, Cell } from '../../../shared/types';

describe('TreeShipGenerator Room Validation', () => {
  const is2x2Room = (map: MapDefinition, x: number, y: number): boolean => {
    // Check if (x,y), (x+1,y), (x,y+1), (x+1,y+1) are all floors
    const cells = [
      map.cells.find(c => c.x === x && c.y === y),
      map.cells.find(c => c.x === x+1 && c.y === y),
      map.cells.find(c => c.x === x && c.y === y+1),
      map.cells.find(c => c.x === x+1 && c.y === y+1)
    ];
    return cells.every(c => c && c.type === CellType.Floor);
  };

  const hasInternalWalls = (map: MapDefinition, x: number, y: number): boolean => {
    const c00 = map.cells.find(c => c.x === x && c.y === y)!;
    const c10 = map.cells.find(c => c.x === x+1 && c.y === y)!;
    const c01 = map.cells.find(c => c.x === x && c.y === y+1)!;
    const c11 = map.cells.find(c => c.x === x+1 && c.y === y+1)!;

    // Check internal boundaries
    // Between (0,0) and (1,0) (East of 00)
    if (c00.walls.e) return true;
    // Between (0,1) and (1,1) (East of 01)
    if (c01.walls.e) return true;
    // Between (0,0) and (0,1) (South of 00)
    if (c00.walls.s) return true;
    // Between (1,0) and (1,1) (South of 10)
    if (c10.walls.s) return true;

    return false;
  };

  it('should generate 2x2 rooms without internal walls', () => {
    // Generate enough maps to likely hit a 2x2 room
    let found2x2 = false;
    for (let i = 0; i < 50; i++) {
        const generator = new TreeShipGenerator(i, 20, 20);
        const map = generator.generate();
        
        for (let y = 0; y < map.height - 1; y++) {
            for (let x = 0; x < map.width - 1; x++) {
                if (is2x2Room(map, x, y)) {
                    // Check if this 2x2 block is actually a room generated by placeRoom
                    // It's hard to know for sure if it's "the" room or just adjacent corridors,
                    // but if we find a 2x2 floor block, it SHOULD ideally be open if it's intended as a room.
                    // However, we are looking for *any* 2x2 block that has internal walls.
                    if (hasInternalWalls(map, x, y)) {
                        throw new Error(`Found 2x2 room with internal walls at seed ${i}, pos (${x},${y})`);
                    }
                    found2x2 = true;
                }
            }
        }
    }
    // We expect to find at least one 2x2 room in 50 iterations
    expect(found2x2).toBe(true);
  });
});
