import { ScreenId } from "@src/renderer/ScreenManager";

export const VALID_TRANSITIONS: Record<ScreenId, ScreenId[]> = {
  "main-menu": [
    "campaign",
    "mission-setup",
    "statistics",
    "mission",
    "settings",
  ],
  campaign: [
    "main-menu",
    "barracks",
    "equipment",
    "mission",
    "mission-setup",
    "campaign-summary",
    "statistics",
    "settings",
  ],
  "mission-setup": [
    "main-menu",
    "equipment",
    "mission",
    "campaign",
    "barracks",
    "statistics",
    "settings",
  ],
  equipment: [
    "campaign",
    "mission-setup",
    "mission",
    "main-menu",
    "barracks",
    "statistics",
    "settings",
  ],
  barracks: ["campaign", "main-menu", "statistics", "settings"],
  mission: ["main-menu", "campaign", "debrief", "campaign-summary"],
  debrief: ["main-menu", "campaign", "campaign-summary", "mission"],
  "campaign-summary": ["main-menu"],
  statistics: ["main-menu", "campaign", "barracks", "settings"],
  settings: [
    "main-menu",
    "campaign",
    "barracks",
    "statistics",
    "mission-setup",
    "equipment",
  ],
};
